### ISSUE TITLE
It cannot be executed except btc-perp

### ISSUE THREAD

**Issue by goushijie** [thibaultyou/grid-bot#3]
1、The docker compose file is as follows:
<img width="219" alt="image" src="https://user-images.githubusercontent.com/7100718/170140074-a061cc15-5b5f-4a84-951c-c92c2cc08f53.png">
2、.evn. eth files are as follows:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/7100718/170140275-175b01df-6993-45d8-b0e5-feeb9d5de1b3.png">
3、eth log files are as follows:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/7100718/170140445-50aa1337-3823-4a78-bd5e-afe7134a18b1.png">
4、If I trade btc-perp is OK, I can't do anything except BTC's trading right

**Comment by thibaultyou** [comment]
Hello there,

One issue can be that on FTX the minimum tradable amount for ETH is 0.001, so you're not supposed to open sell limit orders with 0.0011 ETH as size.

You can also try to remove and rebuild you containers with :

```
sudo docker-compose stop
sudo docker-compose rm
sudo docker-compose up --build -d
```

Hope this helps. :pray:

**Comment by goushijie** [comment]
Thank you very much for reply. I modified FTX the minimum tradable amount for eth is 0.004. This problem still exists
1、.env.eth files:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/7100718/170142101-4cd54dfd-9dfc-448d-a8a1-f8acb486cdf5.png">
2、It's still the same mistake

**Comment by thibaultyou** [comment]
In your case :
BASE_ORDER_SIZE = 0.004 ETH
BUYING_RATIO = 1 -> 0.004 * 1 -> 0.004 ETH buy limit orders
SELLING_RATIO = 1.1 -> 0.004 * 1.1 -> **0.0044** ETH sell limit orders, which can't be processed by FTX.

If you want to use 1.1 as selling ratio you need at least 0.01 as BASE_ORDER_SIZE for ETH. You can also disable overselling by setting SELLING_RATIO to 1.

**Comment by thibaultyou** [comment]
You are also using only two different pairs of API keys / secrets instead of four, since the tool is rotating over keys to avoid FTX API rates limits this can cause some sides effects. The same thing can be encountered if you're sharing keys between two containers.

**Comment by goushijie** [comment]
Thank you very much
1、I try seling_ Ratio = 1 and base_ ORDER_ Size = 0.01, but the problem still exists
<img width="232" alt="image" src="https://user-images.githubusercontent.com/7100718/170143936-d63c18d6-cec1-4b2d-8fb5-f779d883479f.png">
2、I try seling_ Ratio = 1.1 and base_ ORDER_ Size = 0.04, but the problem still exists
<img width="337" alt="image" src="https://user-images.githubusercontent.com/7100718/170144456-5726c9c7-2d71-4162-a27c-30b2a0a34aae.png">

We look forward to your reply

**Comment by thibaultyou** [comment]
Did you tried to stop, rebuild and run again your containers after updating your config ? [1136485052](https://github.com/thibaultyou/grid-bot/issues/3#issuecomment-1136485052)

**Comment by goushijie** [comment]
Yes, I do
`sudo docker-compose stop`
`sudo docker-compose rm`
`sudo docker-compose up --build -d`

**Comment by goushijie** [comment]
1、I have BTC-PERP and ETH-PERP. BTC-PERP is correct, but ETH-PERP still cannot be executed correctly
<img width="974" alt="image" src="https://user-images.githubusercontent.com/7100718/170150215-873ce2f9-6a85-494f-89be-2b3ea564ef0e.png">
2、docker ps ：
<img width="957" alt="image" src="https://user-images.githubusercontent.com/7100718/170150550-79ceb23c-78ba-4494-9038-616eda1bada2.png">
3、BTC-PERP log file
<img width="612" alt="image" src="https://user-images.githubusercontent.com/7100718/170150624-6526f697-b067-4a39-9a53-8d2ebe738f1c.png">
4、ETH-PERP log file
<img width="485" alt="image" src="https://user-images.githubusercontent.com/7100718/170150683-3e4559c8-40ea-456c-ac3a-7e842d96f47c.png">

**I look forward to your suggestions. Thank you very much**

**Comment by goushijie** [comment]
I got the latest logs

`2022-05-25 18:04:22,919 error from callback <function WebsocketWorker._wrap_callback.<locals>.wrapped_f at 0x7fde5cd9e700>: Error running FTX websocket callback: _on_close() takes 3 positional arguments but 5 were given`

**Comment by goushijie** [comment]
**Whether the following exceptions need to be concerned? I know that the transaction can be executed normally，this is  FTX server or network problem?**
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/7100718/170764046-6b15e796-becf-4521-9089-9e4814d7ecff.png">

**Comment by thibaultyou** [comment]
> I got the latest logs
> 
> `2022-05-25 18:04:22,919 error from callback <function WebsocketWorker._wrap_callback.<locals>.wrapped_f at 0x7fde5cd9e700>: Error running FTX websocket callback: _on_close() takes 3 positional arguments but 5 were given`

This is probably related to the function wrapper I've defined [here](https://github.com/thibaultyou/grid-bot/blob/9c360c00ec3e87eb639fb5e2ee755d2dec77bcc9/src/ws.py#L26).

Right now I'm not able to reproduce this issue, but we can add a quick fix to this [line](https://github.com/thibaultyou/grid-bot/blob/9c360c00ec3e87eb639fb5e2ee755d2dec77bcc9/src/ws.py#L99) by adding *args function which will allow optional arguments mentioned above.

`def _on_close(self, ws, event_queue, *args):` should do the trick, can you test this @goushijie and rebuild your containers ?

**Comment by goushijie** [comment]
OK, now everything is perfect. I have a suggestion:
It would be better to add the back test function, so I have more confidence in my trade
